/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOJORDAN2
#define ROOJORDAN2

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooJordan2 : public RooAbsPdf {
public:
  RooJordan2() {} ; 
  RooJordan2(const char *name, const char *title,
	      RooAbsReal& _t,
	      RooAbsReal& _wa,
	      RooAbsReal& _A,
	      RooAbsReal& _tau,
	      RooAbsReal& _phi,
	      RooAbsReal& _N);
  RooJordan2(const RooJordan2& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooJordan2(*this,newname); }
  inline virtual ~RooJordan2() { }

protected:

  RooRealProxy t ;
  RooRealProxy wa ;
  RooRealProxy A ;
  RooRealProxy tau ;
  RooRealProxy phi ;
  RooRealProxy N ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooJordan2,1) // Your description goes here...
};
 
#endif
